### ISSUE TITLE
Why HS_FLAG_SINGLEMATCH can't combination with HS_FLAG_SOM_LEFTMOST

### ISSUE THREAD

**Issue by ipandtcp** [intel/hyperscan#103]
Hi
I was wonder why HS_FLAG_SINGLEMATCH can't combination with HS_FLAG_SOM_LEFTMOST. Because i must set  HS_FLAG_SINGLEMATCH  flag, and i must get "from" value when match_event_handler called. What should i do?
Thanks, best regards.

**Comment by fatchanghao** [comment]
The reason we reject using HS_FLAG_SINGLEMATCH in combine with HS_FLAG_SOM_LEFTMOST is due to our internal design, when you remove this check code, it works in most cases, but may fail in some cases such as matches at EOD position. We will fix this issue in the future.
Thanks,
Harry

**Comment by xjjy1083** [comment]
@fatchanghao Is this restriction only for the stream mode?

**Comment by fatchanghao** [comment]
Unfortunately no, the block mode also has same problem, actually in current version such expression may report match at EOD even it had already reported a match previously, which violates the SINGLE_MATCH behaviour.

**Comment by xjjy1083** [comment]
@fatchanghao When i remove this check code, what was the worst will happend?
1. program crash?
2. match failed?
3. violate the SINGLE_MATCH behaviour?

In most cases, will the matching times be reduced and the performance be improved?

**Comment by fatchanghao** [comment]
@xjjy1083 The worst is 3, no worry about crash or matching failure.

**Comment by pelletier197** [comment]
I have encountered a need for that as well (I don't believe we're on the latest hyperscan however). I was wondering if this had been fixed in latest versions?

**Comment by PLPeeters** [comment]
@fatchanghao This is still happening with the last release; is there still a plan to fix this?
